// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsP-H-759gixOmARtwuQmGbyfWabiatVQ',
    appId: '1:920191534356:web:5f98dd6a8e5e0da1c16e01',
    messagingSenderId: '920191534356',
    projectId: 'riwaa-iq',
    authDomain: 'riwaa-iq.firebaseapp.com',
    databaseURL: 'https://riwaa-iq-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riwaa-iq.firebasestorage.app',
    measurementId: 'G-RM68JHB1QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCufrmtX4vihiXt_dxgBYGT6VgZ4-s1LQk',
    appId: '1:920191534356:android:b9f6191f425ff1c3c16e01',
    messagingSenderId: '920191534356',
    projectId: 'riwaa-iq',
    databaseURL: 'https://riwaa-iq-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riwaa-iq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc3NEpNHEwAw9yZH8_OCo1naJ2cP-oJLw',
    appId: '1:920191534356:ios:1f876b76ac361734c16e01',
    messagingSenderId: '920191534356',
    projectId: 'riwaa-iq',
    databaseURL: 'https://riwaa-iq-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riwaa-iq.firebasestorage.app',
    iosBundleId: 'com.example.riwaa',
  );
}
